### ISSUE TITLE
Getting error "Call to a possibly undefined method construct. (1180)"

### ISSUE THREAD

**Issue by emmaassin** [richardlord/Actionscript-Toolkit#1]
I've used this class in the past with great success - I just copied it over to a new project and I'm getting the error "Call to a possibly undefined method construct. (1180)" objecting to the "construct" method on line 67.  I'm using AIR 33.1.1.633 if there's been some basic change that could have stopped this from working.

**Comment by richardlord** [comment]
The construct method is defined in the file Construct.as so you will need to include this in your new project as well as the ObjectPool class.
